services:
  linkshortener:
    image: ghcr.io/tna76874/urlredirect:latest
    build: .
    ports:
      - "5000:5000"
    container_name: urlredirect-container
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    volumes:
      - ./data:/app/data

